# 请求Google Trends 接口
GET http://127.0.0.1:4444/api/v1/trends/region
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNDExNTQzLCJqdGkiOiIyMjNjNDJhOC0zNmQ4LTRlNDQtYWUxMC04OWEwOGNhMzdlYjIiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE0MTE1NDMsImV4cCI6MTY5MTQxNTE0Mywicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.SdGi3piMbYSXzjmbfL-DLTKrk5zUXV9xLDInNcrcA6w

{
  "keyword": "new",
  "timeframe": "all"
}
###
GET http://127.0.0.1:4444/api/v1/trends/categories
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNDExNTQzLCJqdGkiOiIyMjNjNDJhOC0zNmQ4LTRlNDQtYWUxMC04OWEwOGNhMzdlYjIiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE0MTE1NDMsImV4cCI6MTY5MTQxNTE0Mywicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.SdGi3piMbYSXzjmbfL-DLTKrk5zUXV9xLDInNcrcA6w
###
GET http://127.0.0.1:4444/api/v1/trends/suggestions
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNTgzOTc4LCJqdGkiOiI1ZGNhNmViYS00MmExLTRiM2YtYWI5OS03OTUwZjUxMzZmZTYiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE1ODM5NzgsImV4cCI6MTY5MTU4NzU3OCwicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.M2yUuBi9h4efWe3bED0fuDsrYPPx8rFG--Zp0yVFQIk

{
  "q": "new"
}
###
POST http://127.0.0.1:4444/api/v1/trends/overTime
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNDExNTQzLCJqdGkiOiIyMjNjNDJhOC0zNmQ4LTRlNDQtYWUxMC04OWEwOGNhMzdlYjIiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE0MTE1NDMsImV4cCI6MTY5MTQxNTE0Mywicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.SdGi3piMbYSXzjmbfL-DLTKrk5zUXV9xLDInNcrcA6w

{
  "keyword": "new",
  "timeframe": "all"

}
###
POST http://127.0.0.1:4444/api/v1/trends/queries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNDExNTQzLCJqdGkiOiIyMjNjNDJhOC0zNmQ4LTRlNDQtYWUxMC04OWEwOGNhMzdlYjIiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE0MTE1NDMsImV4cCI6MTY5MTQxNTE0Mywicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.SdGi3piMbYSXzjmbfL-DLTKrk5zUXV9xLDInNcrcA6w

{
  "keyword": "new",
  "timeframe": "all"

}

###
POST http://127.0.0.1:4444/api/v1/trends/topics
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6dHJ1ZSwiaWF0IjoxNjkxNDExNTQzLCJqdGkiOiIyMjNjNDJhOC0zNmQ4LTRlNDQtYWUxMC04OWEwOGNhMzdlYjIiLCJ0eXBlIjoiYWNjZXNzIiwic3ViIjoxLCJuYmYiOjE2OTE0MTE1NDMsImV4cCI6MTY5MTQxNTE0Mywicm9sZSI6ImFkbWluIiwiaXNfdmVyaWZpZWQiOnRydWV9.SdGi3piMbYSXzjmbfL-DLTKrk5zUXV9xLDInNcrcA6w

{
  "keyword": "new",
  "timeframe": "all"
}